### ISSUE TITLE
Create Invoice Method Call Issue in Invalid Parameters :status code 400 

### ISSUE THREAD

**Issue by chandrakantjadhav** [cubits/cubits-php#4]
Fatal error: Uncaught exception 'Cubits_ApiException' with message 'Status code {"message":"Invalid parameters"}' in C:\xampp\htdocs\DEV\bitwiseAPI\cubits\lib\Cubits\Requestor.php:22 Stack trace: #0 C:\xampp\htdocs\DEV\bitwiseAPI\cubits\lib\Cubits\Rpc.php(104): Cubits_Requestor->doCurlRequest(Resource id #13) #1 C:\xampp\htdocs\DEV\bitwiseAPI\cubits\lib\Cubits\Cubits.php(52): Cubits_Rpc->request('POST', 'invoices', Array) #2 C:\xampp\htdocs\DEV\bitwiseAPI\cubits\lib\Cubits\Cubits.php(110): Cubits->post('invoices', Array) #3 C:\xampp\htdocs\DEV\bitwiseAPI\cubits\lib\Cubits\Cubits.php(104): Cubits->createInvoiceWithOptions(Array) #4 C:\xampp\htdocs\DEV\bitwiseAPI\cubits\demos\test\post_test.php(12): Cubits->createInvoice('Your Order #123...', '42.95', 'EUR', Array) #5 {main} thrown in C:\xampp\htdocs\DEV\bitwiseAPI\cubits\lib\Cubits\Requestor.php on line 22

![bitcoinapiissue](https://cloud.githubusercontent.com/assets/27028609/24818782/777436de-1bff-11e7-9576-8b37044b33ed.PNG)

Please help me out with same!!

**Comment by kukushkin** [comment]
@chandrakantjadhav the reason for ```"message":"Invalid parameters"``` can be that your account is blocked. Could you contact support @cubits.com and report your issue there? 

For now I'm closing this issue. In case you discover that your account is NOT actually blocked and the problem persists, please reopen the issue here again.
